version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 897621100871.dkr.ecr.us-east-1.amazonaws.com
      - aws codeartifact login --tool npm --domain-owner 897621100871 --domain chrt --repository chrt-npm-packages
      - npm install
  build:
    commands:
      - docker build -t chrt-express-postgres-tradingdata .
      - docker tag chrt-express-postgres-tradingdata:latest 897621100871.dkr.ecr.us-east-1.amazonaws.com/chrt-express-postgres-tradingdata:latest
  post_build:
    commands:
      - docker push 897621100871.dkr.ecr.us-east-1.amazonaws.com/chrt-express-postgres-tradingdata:latest
      - printf '[{"name":"chrt-express-postgres-tradingdata","imageUri":"897621100871.dkr.ecr.us-east-1.amazonaws.com/chrt-express-postgres-tradingdata:latest"}' > imagedefinitions.json
artifacts:
files: imagedefinitions.json
